"""empty message

Revision ID: 2617a228f5fb
Revises: 2487ebe9d5a1
Create Date: 2020-01-22 19:44:56.242125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2617a228f5fb'
down_revision = '2487ebe9d5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msg_history', sa.Column('user', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('msg_history', 'user')
    # ### end Alembic commands ###
