"""empty message

Revision ID: 8ac2461d97eb
Revises: 578281619467
Create Date: 2020-01-18 09:17:35.061635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac2461d97eb'
down_revision = '578281619467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suggestion', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggestion', type_='foreignkey')
    op.drop_column('suggestion', 'author_id')
    # ### end Alembic commands ###
