"""empty message

Revision ID: bbaa5feec234
Revises: 2a7d14cc8a54
Create Date: 2020-01-31 16:51:16.358983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbaa5feec234'
down_revision = '2a7d14cc8a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggestion', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'suggestion', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
